---
- name: Setup Docker environment locally
  hosts: localhost
  connection: local
  become: yes

  vars:
    docker_compose_version: "1.29.2"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required system packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Set Docker Compose binary URL
      set_fact:
        docker_compose_url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"

    - name: Download Docker Compose binary
      get_url:
        url: "{{ docker_compose_url }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Create app directory
      file:
        path: /opt/myapp
        state: directory

    - name: Copy docker-compose.yml
      copy:
        src: files/docker-compose.yml
        dest: /opt/myapp/docker-compose.yml

    - name: Run Docker Compose
      shell: docker-compose up -d
      args:
        chdir: /opt/myapp
